### ISSUE TITLE
Broken dependency on `humanize.abs_timedelta`

### ISSUE THREAD

**Issue by webbnh** [metwork-framework/jinja2_humanize_extension#4]
As of v4.0.0 of `humanize`, [`abs_timedelta()` is deprecated](https://github.com/jmoiron/humanize/commit/2482af79f3367d6ddbfb68edd918a9e358f09cee).

My installation (`humanize-4.0.0`, `jinja2-3.0.3`, `jinja2-humanize-extension-0.2.0`) produces this:
```
Traceback (most recent call last):
  File "/var/tmp/pbench-test-server/test-2/opt/pbench-server/bin/pbench-tarball-stats.py", line 325, in <module>
    status = main(parsed)
  File "/var/tmp/pbench-test-server/test-2/opt/pbench-server/bin/pbench-tarball-stats.py", line 297, in main
    env = jinja2.Environment(
  File "/var/tmp/tox/jenkins-unittests/lib/python3.9/site-packages/jinja2/environment.py", line 362, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/var/tmp/tox/jenkins-unittests/lib/python3.9/site-packages/jinja2/environment.py", line 118, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/var/tmp/tox/jenkins-unittests/lib/python3.9/site-packages/jinja2/utils.py", line 215, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/var/tmp/tox/jenkins-unittests/lib/python3.9/site-packages/jinja2_humanize_extension/__init__.py", line 5, in <module>
    from humanize.time import (
ImportError: cannot import name 'abs_timedelta' from 'humanize.time' (/var/tmp/tox/jenkins-unittests/lib/python3.9/site-packages/humanize/time.py)
```

**Comment by thebaptiste** [comment]
We will release 0.2.1 with this fix soon

**Comment by webbnh** [comment]
Thanks!  (Your turnaround on fixing this is very much appreciated! 😁)
